import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output, OnInit } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'gls-language-modal',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  templateUrl: './gls-language-modal.component.html',
  styleUrl: './gls-language-modal.component.scss'
})
export class GlsLanguageModalComponent implements OnInit {
  @Input() data!: string;
  @Output() dataChange = new EventEmitter<string>();
  selectLang!: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  langList: any[] = [
    { code: 'it', name: 'Italiano' },
    { code: 'en', name: 'English' }
  ];
  constructor(
    private activeModal: NgbActiveModal,
    private translateService: TranslateService
  ) {
    // Autogenerated constructor
  }

  ngOnInit(): void {
    this.selectLang = this.data;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onSelectChange(lang: any) {
    this.selectLang = lang;
  }

  closeModal() {
    this.activeModal.close(false);
  }

  /**
   * get the selcted language value
   */
  save() {
    this.translateService.use(this.selectLang);
    this.activeModal.close(true);
    this.dataChange.emit(this.selectLang);
  }
}
