import { CommonModule } from '@angular/common';
import { Component, EventEmitter, inject, Input, OnInit, Output } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';
import { Breadcrumb, BreadcrumbService } from '../../utilities/services/breadcrumb/breadcrumb.service';
import { ChangeLangComponent } from '../change-lang/change-lang.component';
import { UserDetailComponent } from '../user-detail/user-detail.component';
import { GenericService } from '../../utilities/services/generic.service';
import { VIEW_MODE } from '../../app.constants';
import { UtilityRouting } from '../../utilities/utility-routing';

@Component({
  selector: 'gls-top-menu',
  standalone: true,
  imports: [CommonModule, TranslateModule, ChangeLangComponent, UserDetailComponent],
  templateUrl: './gls-top-menu.component.html',
  styleUrl: './gls-top-menu.component.scss'
})
export class GlsTopMenuComponent implements OnInit {
  @Input() isIconEnabled?: boolean = false;
  @Output() toggleSidebar = new EventEmitter<void>();
  isSmallScreen = false;
  private readonly genericService = inject(GenericService);

  breadcrumb: Breadcrumb[] = [{ label: 'breadcrumb.home', url: '/home' }];

  constructor(private breadcrumbService: BreadcrumbService) {
    // Autogenerated
  }

  ngOnInit() {
    this.breadcrumbService.getBreadcrumbs().subscribe((breadcrumbList: Breadcrumb[]) => {
      this.breadcrumb = breadcrumbList;
    });
    this.isSmallScreen = this.genericService.viewMode() === VIEW_MODE.MOBILE;
  }

  toggleNavIcon() {
    this.toggleSidebar.emit();
  }

  navigateTo(url: string): void {
    UtilityRouting.navigateByUrl(url);
  }
}
