export const ICONS: Record<string, string> = {
  cityDepot: 'assets/img/transparent/PNG-City Depot_SVG_RGB_Blue.png',
  conveyBelt: 'assets/img/transparent/PNG-Convey belt_blue.png',
  corporateOffice: 'assets/img/transparent/PNG-Corporate office_blue.png',
  depot: 'assets/img/transparent/PNG-Depot_blue.png',
  driver: 'assets/img/transparent/PNG-Driver_blue.png',
  eCar: 'assets/img/transparent/PNG-eCar_blue.png',
  eDepot: 'assets/img/transparent/PNG-eDepot_blue.png',
  eHub: 'assets/img/transparent/PNG-eHub_blue.png',
  electricChargingStation: 'assets/img/transparent/PNG-Electric charging station_blue.png',
  employeeTeam: 'assets/img/transparent/PNG-Employee - Team_blue.png',
  eVan: 'assets/img/transparent/PNG-eVan_blue.png',
  flight: 'assets/img/transparent/PNG-Flight_blue.png',
  hub: 'assets/img/transparent/PNG-Hub_blue.png',
  internationalCrossBorder: 'assets/img/transparent/PNG-International - Cross border_blue.png',
  journeyItinerary: 'assets/img/transparent/PNG-Journey - Itinerary_blue.png',
  parcelLocker: 'assets/img/transparent/PNG-Parcel locker_blue.png',
  parcelShop: 'assets/img/transparent/PNG-Parcel shop_blue.png',
  parcel: 'assets/img/transparent/PNG-Parcel_blue.png',
  recipientHouse: 'assets/img/transparent/PNG-Recipient - House_blue.png',
  redirection: 'assets/img/transparent/PNG-Redirection_blue.png',
  return: 'assets/img/transparent/PNG-Return_blue.png',
  safeAndFastDeliveries: 'assets/img/transparent/PNG-Safe and fast deliveries_blue.png',
  send: 'assets/img/transparent/PNG-Send_blue.png',
  ship: 'assets/img/transparent/PNG-Ship_blue.png',
  tracking: 'assets/img/transparent/PNG-Tracking_blue.png',
  train: 'assets/img/transparent/PNG-Train_blue.png',
  van: 'assets/img/transparent/PNG-Van_blue.png'
};
