import { CommonModule } from '@angular/common';
import { Component, Inject } from '@angular/core';
import { NgbActiveModal, NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { TranslateModule } from '@ngx-translate/core';
import { UtilityRouting } from '../../utilities/utility-routing';

@Component({
  selector: 'app-authorization-error-modal',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  templateUrl: './authorization-error-modal.component.html',
  styleUrl: './authorization-error-modal.component.scss'
})
export class AuthorizationErrorModalComponent {
  constructor(
    private readonly activeModal: NgbActiveModal,
    @Inject(NgbModal) public errorCode: number
  ) {
    // Autogenerated constructor
  }

  getMessage(): string {
    if (this.errorCode === 401) {
      return 'modal.serviceMessage.httpErrors.401';
    } else if (this.errorCode === 403) {
      return 'modal.serviceMessage.httpErrors.403';
    }

    return 'modal.serviceMessage.genericError';
  }

  /**
   * Closes the modal and signals the parent component to reload the application.
   *
   * This method is triggered when the "Reload" button is clicked in the modal.
   * It closes the modal by calling `activeModal.close(true)` and passes a `true` value
   * to indicate that the reload action should be performed.
   */
  reload(): void {
    this.activeModal.close(true);
    UtilityRouting.relocateToHome();
  }
}
